version: 2

models:
  - name: fact_historical_trips
    description: >
      Information about each trip, 
    columns:
      - name: trip_id
        description: XXXXXXXX
        data_type: text
        data_tests:
          - not_null
      - name: stop_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: line_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: route_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: direction_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: date
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: average_velocity
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: average_distance
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: average_time
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
  - name: dim_date
    description: Dimension table about the date.
    columns:
      - name: date_day
        description: Date.
      - name: prior_date_day
        description: Date of the previous day.
      - name: next_date_day
        description: Date of the next day.
      - name: prior_year_date_day
        description: Date of the same day in the previous year.
      - name: prior_year_over_year_date_day
        description: Date of the same day in the year before the previous year.
      - name: day_of_week
        description: Day of the week.
      - name: day_of_week_name
        description: Name of the day of the week.
      - name: day_of_week_name_short
        description: Short name of the day of the week.
      - name: day_of_month
        description: Day of the month.
      - name: day_of_year
        description: Day of the year.
      - name: week_start_date
        description: Start date of the week.
      - name: week_end_date
        description: End date of the week.
      - name: prior_year_week_start_date
        description: Start date of the week in the previous year.
      - name: prior_year_week_end_date
        description: End date of the week in the previous year.
      - name: week_of_year
        description: Week of the year.
      - name: iso_week_start_date
        description: Start date of the ISO week.
      - name: iso_week_end_date
        description: End date of the ISO week.
      - name: prior_year_iso_week_start_date
        description: Start date of the ISO week in the previous year.
      - name: prior_year_iso_week_end_date
        description: End date of the ISO week in the previous year.
      - name: iso_week_of_year
        description: ISO week of the year.
      - name: prior_year_week_of_year
        description: Week of the year in the previous year.
      - name: prior_year_iso_week_of_year
        description: ISO week of the year in the previous year.
      - name: month_of_year
        description: Month of the year.
      - name: month_name
        description: Name of the month.
      - name: month_name_short
        description: Short name of the month.
      - name: month_start_date
        description: Start date of the month.
      - name: month_end_date
        description: End date of the month.
      - name: prior_year_month_start_date
        description: Start date of the month in the previous year.
      - name: prior_year_month_end_date
        description: End date of the month in the previous year.
      - name: quarter_of_year
        description: Quarter of the year.
      - name: quarter_start_date
        description: Start date of the quarter.
      - name: quarter_end_date
        description: End date of the quarter.
      - name: year_number
        description: Year number.
      - name: year_start_date
        description: Start date of the year.
      - name: year_end_date
        description: End date of the year.
      - name: ingested_at
        description: Timestamp when the data was ingested.