version: 2

models:
  - name: fact_historical_trips
    description: >
      Information about each trip, XXXX
    columns:
      - name: trip_id
        description: XXXXXXXX
        data_type: text
        data_tests:
          - not_null
      - name: stop_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: line_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: route_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: direction_id
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: date
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: average_velocity
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: average_distance
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null
      - name: average_time
        description: XXXXXXXX
        data_type: numeric
        data_tests:
          - not_null