version: 2

models:
  - name: fact_historical_trips
    description: >
      Information about each trip, 
    columns:
      - name: trip_id
        description: Unique identifier for each trip.
        data_type: numeric
        data_tests:
          - not_null
      - name: line_id
        description: Identify the line for each trip.
        data_type: numeric
        data_tests:
          - not_null
      - name: stop_id
        description: Identify the stops made for each trip.
        data_type: numeric
        data_tests:
          - not_null
      - name: trip_date
        description: Date ('YYYY-MM-DD') on which the trip took place. 
        data_type: numeric
        data_tests:
          - not_null
      - name: trip_stops
        description: Number of stops for each trip.
        data_type: numeric
        data_tests:
          - not_null
      - name: trip_total_distance_km
        description: Total distance for each trip, in kilometers.
        data_type: numeric
        data_tests:
          - not_null
      - name: trip_total_time_min
        description: Total time for each trip, in minutes.
        data_type: numeric
        data_tests:
          - not_null
      - name: trip_avg_speed
        description: Average velocity for each trip, in kilometers per minutes.
        data_type: numeric
        data_tests:
          - not_null
  - name: dim_date
    description: Dimension table about the date.
    columns:
      - name: date_day
        description: Date.
      - name: prior_date_day
        description: Date of the previous day.
      - name: next_date_day
        description: Date of the next day.
      - name: prior_year_date_day
        description: Date of the same day in the previous year.
      - name: prior_year_over_year_date_day
        description: Date of the same day in the year before the previous year.
      - name: day_of_week
        description: Day of the week.
      - name: day_of_week_name
        description: Name of the day of the week.
      - name: day_of_week_name_short
        description: Short name of the day of the week.
      - name: day_of_month
        description: Day of the month.
      - name: day_of_year
        description: Day of the year.
      - name: week_start_date
        description: Start date of the week.
      - name: week_end_date
        description: End date of the week.
      - name: prior_year_week_start_date
        description: Start date of the week in the previous year.
      - name: prior_year_week_end_date
        description: End date of the week in the previous year.
      - name: week_of_year
        description: Week of the year.
      - name: iso_week_start_date
        description: Start date of the ISO week.
      - name: iso_week_end_date
        description: End date of the ISO week.
      - name: prior_year_iso_week_start_date
        description: Start date of the ISO week in the previous year.
      - name: prior_year_iso_week_end_date
        description: End date of the ISO week in the previous year.
      - name: iso_week_of_year
        description: ISO week of the year.
      - name: prior_year_week_of_year
        description: Week of the year in the previous year.
      - name: prior_year_iso_week_of_year
        description: ISO week of the year in the previous year.
      - name: month_of_year
        description: Month of the year.
      - name: month_name
        description: Name of the month.
      - name: month_name_short
        description: Short name of the month.
      - name: month_start_date
        description: Start date of the month.
      - name: month_end_date
        description: End date of the month.
      - name: prior_year_month_start_date
        description: Start date of the month in the previous year.
      - name: prior_year_month_end_date
        description: End date of the month in the previous year.
      - name: quarter_of_year
        description: Quarter of the year.
      - name: quarter_start_date
        description: Start date of the quarter.
      - name: quarter_end_date
        description: End date of the quarter.
      - name: year_number
        description: Year number.
      - name: year_start_date
        description: Start date of the year.
      - name: year_end_date
        description: End date of the year.
      - name: ingested_at
        description: Timestamp when the data was ingested.
  - name: dim_trips
    columns:
      - name: trip_id
        description: Identifies a trip.
        data_type: text
        data_tests:
          - not_null 
      - name: line_id
        description: Identifies a line.
        data_type: numeric
        data_tests:
          - not_null
      - name: line_name
        description: Names the line.
        data_type: text
        data_tests:
          - not_null
      - name: route_id
        description: Identifies a route.
        data_type: text
        data_tests:
          - not_null
      - name: route_name
        description: Names the route.
        data_type: text
        data_tests:
          - not_null
      - name: direction_id
        description: Indicates the direction of travel for a trip. 
        data_type: integer
        data_tests:
          - not_null
          - accepted_values:
              values:
                - 0
                - 1
  - name: dim_stops
    columns:
      - name: stop_id
        description: Identifies the stop.
        data_type: numeric
        data_tests:
          - not_null 
      - name: stop_name
        description: Names the bus stop.
        data_type: text
        data_tests:
          - not_null 
      - name: municipality_id
        description: Identifies the municipality.
        data_type: numeric
        data_tests:
          - not_null 
      - name: municipality_name
        description: Names the municipality.
        data_type: text
        data_tests:
          - not_null 
      - name: region_name
        description: Names the region in which the municipality is located.
        data_type: text
        data_tests:
          - not_null 
      - name: operational_status
        description: Informs if the stop is operational.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - ACTIVE
                - INACTIVE